# Generated by Django 6.0.3 on 2026-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_options_rename_buyer_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
